# - Try to find STORMLIB
# Once done this will define
#  STORMLIB_FOUND - System has STORMLIB
#  STORMLIB_INCLUDE_DIR - The STORMLIB include directory
#  STORMLIB_LIBRARY - The library needed to use STORMLIB

find_path(STORMLIB_INCLUDE_DIR NAMES StormLib.h StormPort.h PATHS ${CMAKE_SOURCE_DIR}/depends/stormlib/include)
find_library(STORMLIB_LIBRARIES NAMES stormlib StormLib libstorm storm PATHS ${CMAKE_SOURCE_DIR}/depends/stormlib )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STORMLIB DEFAULT_MSG STORMLIB_INCLUDE_DIR STORMLIB_LIBRARIES)
mark_as_advanced(STORMLIB_INCLUDE_DIR STORMLIB_LIBRARIES)

set(STORMLIB_INCLUDE_DIRS ${STORMLIB_INCLUDE_DIR})

set(STORMLIB_PATH "")
FOREACH(LIB_NAME ${STORMLIB_LIBRARIES})
	get_filename_component(LDIR ${LIB_NAME} DIRECTORY)
	set(STORMLIB_PATH "${STORLMIB_PATH};${LDIR}")
ENDFOREACH()

MESSAGE(STATUS "STORMLIB include: " ${STORMLIB_INCLUDE_DIRS})
MESSAGE(STATUS "STORMLIB expanded path: " ${STORMLIB_PATH})
MESSAGE(STATUS "STORMLIB lib: " ${STORMLIB_LIBRARIES})

